name: PHP Code Linting

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  php-lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate Composer configuration
        run: composer validate

      - name: Install PHP dependencies
        uses: ramsey/composer-install@83af392bf5f031813d25e6fe4cd626cdba9a2df6
        with:
          composer-options: '--prefer-dist --no-progress --no-interaction'

      - name: Run tests
        run: composer run-script phpcs
